# -*- python -*-
Import('env')
import glob
import os

pkg = env["eups_product"]

cFiles = ['../src/levmar/Axb.c', '../src/levmar/lm.c', '../src/levmar/misc.c']

env.SharedLibrary(
    pkg,
    glob.glob("../src/*.cc") + glob.glob("../src/*/*.cc") + cFiles,
    LIBS=filter(lambda p: p != pkg, env.getlibs(pkg)),
)
