# -*- python -*-
Import('env')
import glob
import os

pkg = env["eups_product"]

env.SharedLibrary(
    pkg,
    glob.glob("../src/*.cc") + glob.glob("../src/*/*.cc"),
    LIBS=filter(lambda p: p != pkg, env.getlibs(pkg)),
)
