# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.python(['_modelfitLib'], [
    '_modelfitLib.cc',
    'adaptiveImportanceSampler.cc',
    'cmodel/cmodel.cc',
    'integrals.cc',
    'likelihood.cc',
    'mixture.cc',
    'model.cc',
    'multiModel.cc',
    'optimizer/optimizer.cc',
    'pixelFitRegion/pixelFitRegion.cc',
    'priors/priors.cc',
    'psf/psf.cc',
    'sampler.cc',
    'truncatedGaussian.cc',
    'unitSystem.cc',
    'unitTransformedLikelihood.cc']
)
