# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['mixture',
     'unitSystem',
     'priors/priors',
     'model',
     'multiModel',
     'likelihood',
     'sampler',
     'adaptiveImportanceSampler',
     'optimizer/optimizer',
     'psf/psf',
     'pixelFitRegion/pixelFitRegion',
     'truncatedGaussian',
     'integrals',
     'unitTransformedLikelihood',
     'cmodel/cmodel',
     'regularizedMoments/regularizedMoments',
     ],
    addUnderscore=False
)
