# -*- python -*-
Import("env")

pkg = env["eups_product"]
env.CheckSwig("python", ilang="c++", includedProducts="utils pex_exceptions afw meas_algorithms")
env.LoadableModuleIncomplete("_multifitLib", Split("multifitLib.i"), LIBS=env.getlibs(pkg))
