# -*- python -*-
Import("env")

pkg = env["eups_product"]
env.CheckSwig("python", ilang="c++", 
            includedProducts="utils daf_base daf_data daf_persistence pex_logging pex_policy pex_exceptions security afw meas_algorithms")
env.LoadableModuleIncomplete("_multifitLib", Split("multifitLib.i"), LIBS=env.getlibs(pkg))
