# -*- python -*-
Import("env")
import glob
	
#
# Tests
#
import lsst.tests

# This is failing to solve for some unknown reason.
ignoreList = ["WcsDeterminationTest.py"]
tests = lsst.tests.Control(env, ignoreList=ignoreList, verbose = True)
tests.run("*.py")
